version: '3'

services:
  work:
    build:
      context: ./work
      dockerfile: Dockerfile
    volumes:
      - ./work/:/work/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - record
    restart: "on-failure"

  record:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: "on-failure"

volumes:
    postgres_data: